# Generated by Django 4.2.5 on 2023-09-06 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=32, unique=True)),
                ('hall_place', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('description', models.TextField(null=True, verbose_name='Описание мероприятия')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Дата проведения')),
                ('begin_time', models.TimeField(verbose_name='Время начала')),
                ('finish_time', models.TimeField(verbose_name='Время окончания')),
                ('logo', models.FilePathField(null=True, path='/images', verbose_name='Logo')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.halls')),
            ],
        ),
    ]
