# Generated by Django 4.2.5 on 2023-09-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_halls_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.FileField(upload_to='images/', verbose_name='Logo'),
        ),
    ]
