# Generated by Django 4.2.5 on 2023-10-12 07:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_room_location_event_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_in_list', models.CharField(max_length=32, unique=True)),
                ('name_in_list_eng', models.CharField(max_length=32, null=True)),
                ('hall_in_list_place', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Зал в списке',
                'verbose_name_plural': 'Залы в списке',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='begin_time',
            field=models.TimeField(default='09:00', verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 10, 13, 10, 0, 6, 974486), verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='finish_time',
            field=models.TimeField(default='18:00', verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.FileField(blank=True, upload_to='images/', verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='LocList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('halllist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.halllist')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='room_in_list',
            field=models.ManyToManyField(through='events.LocList', to='events.halllist', verbose_name='Отображение в списке'),
        ),
    ]
