# Generated by Django 4.2.5 on 2024-02-07 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_halllist_alter_event_begin_time_alter_event_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 9, 43, 15, 263378), verbose_name='Дата проведения'),
        ),
    ]
