# Generated by Django 4.2.5 on 2024-02-07 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_mail_alter_event_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Менеджер')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Список рассылки', 'verbose_name_plural': 'Список рассылки'},
        ),
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='Контакт организатора'),
        ),
        migrations.AddField(
            model_name='event',
            name='parking',
            field=models.CharField(blank=True, max_length=255, verbose_name='Парковка'),
        ),
        migrations.AddField(
            model_name='event',
            name='quantity',
            field=models.CharField(default='n/a', max_length=5, verbose_name='Колличество участников'),
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 12, 30, 45, 133378), verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Компания'),
        ),
    ]
