# Generated by Django 4.2.5 on 2024-02-07 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_manager_alter_mail_options_event_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='responce',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.manager', verbose_name='Ответственный'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.DateField(default=datetime.datetime(2024, 2, 8, 12, 34, 34, 739378), verbose_name='Дата проведения'),
        ),
    ]
